from __future__ import annotations

from datetime import datetime

from neo4j import Driver


ALLOWED_REVIEW_STATUSES = {
    "NEW",
    "UNDER_REVIEW",
    "CONFIRMED",
    "REJECTED",
}


def to_python_datetime(value):
    """
    Convert Neo4j temporal values to standard Python datetime.
    Leave normal Python datetime / None unchanged.
    """

    if value is None:
        return None

    if isinstance(value, datetime):
        return value

    if hasattr(value, "to_native"):
        return value.to_native()

    return value


def clean_subjects(
    subjects: list[dict | None] | None,
) -> list[dict]:
    """
    Remove null/invalid subjects returned by OPTIONAL MATCH.
    """

    cleaned = []

    for subject in subjects or []:

        if not subject:
            continue

        entity_id = subject.get(
            "entity_id"
        )

        name = subject.get(
            "name"
        )

        if entity_id is None:
            continue

        cleaned.append(
            {
                "entity_id": str(entity_id),
                "name": (
                    str(name)
                    if name is not None
                    else None
                ),
            }
        )

    return cleaned


def build_description(
    finding_type: str,
    record: dict,
) -> str:

    description = record.get(
        "description"
    )

    if description:
        return description

    if finding_type == "TEMPORAL_COORDINATION":

        return (
            f"{record.get('participant_count', 0)} "
            f"participants were observed at "
            f"{record.get('location_name', 'unknown location')} "
            f"within "
            f"{record.get('window_seconds', 0)} seconds."
        )

    return (
        "Investigative finding generated by NEXUS."
    )


def list_findings(
    driver: Driver,
) -> list[dict]:

    with driver.session() as session:

        result = session.run(
            """
            MATCH (f:Finding)

            OPTIONAL MATCH
                (p:Person)-[
                    :SUBJECT_OF
                    |PARTICIPANT_IN
                ]->(f)

            WITH
                f,
                collect(
                    DISTINCT CASE
                        WHEN p IS NULL THEN NULL
                        ELSE {
                            entity_id:
                                p.person_id,
                            name:
                                p.name
                        }
                    END
                ) AS subjects

            RETURN
                f.finding_id AS finding_id,
                f.finding_type AS finding_type,
                f.status AS status,
                f.description AS description,
                f.model AS model,
                f.anomaly_score AS model_score,
                f.location_name AS location_name,
                f.participant_count AS participant_count,
                f.window_start AS window_start,
                f.window_end AS window_end,
                subjects

            ORDER BY
                finding_id
            """
        )

        findings = []

        for record in result:

            data = record.data()

            data["subjects"] = clean_subjects(
                data.get("subjects")
            )

            data["description"] = (
                build_description(
                    data["finding_type"],
                    data,
                )
            )

            data["window_start"] = (
                to_python_datetime(
                    data.get("window_start")
                )
            )

            data["window_end"] = (
                to_python_datetime(
                    data.get("window_end")
                )
            )

            findings.append(data)

        return findings


def get_finding(
    driver: Driver,
    finding_id: str,
) -> dict | None:

    with driver.session() as session:

        result = session.run(
            """
            MATCH (
                f:Finding {
                    finding_id: $finding_id
                }
            )

            OPTIONAL MATCH
                (p:Person)-[
                    :SUBJECT_OF
                    |PARTICIPANT_IN
                ]->(f)

            WITH
                f,
                collect(
                    DISTINCT CASE
                        WHEN p IS NULL THEN NULL
                        ELSE {
                            entity_id:
                                p.person_id,
                            name:
                                p.name
                        }
                    END
                ) AS subjects

            RETURN
                f.finding_id AS finding_id,
                f.finding_type AS finding_type,
                f.status AS status,
                f.description AS description,
                f.reasons AS reasons,
                f.model AS model,
                f.anomaly_score AS model_score,
                f.location_name AS location_name,
                f.location_id AS location_id,
                f.participant_count AS participant_count,
                f.participants AS participants,
                f.window_start AS window_start,
                f.window_end AS window_end,
                f.window_seconds AS window_seconds,
                f.evidence_ids AS evidence_ids,
                f.case_ids AS case_ids,
                f.method AS method,
                f.review_notes AS review_notes,
                subjects
            """,
            finding_id=finding_id,
        )

        record = result.single()

        if record is None:
            return None

        data = record.data()

        data["subjects"] = clean_subjects(
            data.get("subjects")
        )

        data["description"] = (
            build_description(
                data["finding_type"],
                data,
            )
        )

        data["reasons"] = (
            data.get("reasons")
            or []
        )

        data["case_ids"] = (
            data.get("case_ids")
            or []
        )

        data["evidence_ids"] = (
            data.get("evidence_ids")
            or []
        )

        data["participants"] = (
            data.get("participants")
            or []
        )

        data["window_start"] = (
            to_python_datetime(
                data.get("window_start")
            )
        )

        data["window_end"] = (
            to_python_datetime(
                data.get("window_end")
            )
        )

        data["evidence"] = (
            load_finding_evidence(
                session,
                data,
            )
        )

        return data


def load_finding_evidence(
    session,
    finding: dict,
) -> list[dict]:

    evidence_ids = (
        finding.get(
            "evidence_ids"
        )
        or []
    )

    evidence = []

    if not evidence_ids:
        return evidence

    finding_type = finding[
        "finding_type"
    ]

    subject_ids = [
        subject["entity_id"]
        for subject
        in finding.get(
            "subjects",
            []
        )
    ]

    if finding_type == (
        "TEMPORAL_COORDINATION"
    ):

        location_id = finding.get(
            "location_id"
        )

        participants = (
            finding.get(
                "participants"
            )
            or subject_ids
        )

        if location_id:

            result = session.run(
                """
                MATCH
                    (p:Person)
                        -[r:SEEN_AT]->
                    (l:Location {
                        location_id:
                            $location_id
                    })

                WHERE
                    p.person_id IN $participants
                    AND r.evidence_id IN
                        $evidence_ids

                RETURN
                    r.evidence_id
                        AS evidence_id,
                    "SURVEILLANCE"
                        AS source_type,
                    r.timestamp
                        AS timestamp,
                    r.case_id
                        AS case_id

                ORDER BY
                    r.timestamp
                """,
                location_id=location_id,
                participants=participants,
                evidence_ids=evidence_ids,
            )

            records = []

            for record in result:

                item = record.data()

                item["timestamp"] = (
                    to_python_datetime(
                        item.get("timestamp")
                    )
                )

                records.append(item)

            return records

    elif finding_type == "ANOMALY":

        result = session.run(
            """
            MATCH
                (p:Person)
                    -[:OWNS]->
                (ph:Phone)
                    -[c:CALLS]->()

            WHERE
                p.person_id IN $subject_ids
                AND c.evidence_id IN
                    $evidence_ids

            RETURN DISTINCT
                c.evidence_id
                    AS evidence_id,
                "CDR"
                    AS source_type,
                c.timestamp
                    AS timestamp,
                c.case_id
                    AS case_id

            ORDER BY
                c.timestamp
            """,
            subject_ids=subject_ids,
            evidence_ids=evidence_ids,
        )

        records = []

        for record in result:

            item = record.data()

            item["timestamp"] = (
                to_python_datetime(
                    item.get("timestamp")
                )
            )

            records.append(item)

        return records

    return evidence


def review_finding(
    driver: Driver,
    finding_id: str,
    status: str,
    review_notes: str | None,
) -> dict | None:

    if status not in ALLOWED_REVIEW_STATUSES:

        raise ValueError(
            "Invalid finding status."
        )

    with driver.session() as session:

        result = session.run(
            """
            MATCH (
                f:Finding {
                    finding_id:
                        $finding_id
                }
            )

            SET
                f.status =
                    $status,
                f.review_notes =
                    $review_notes,
                f.reviewed_at =
                    datetime()

            RETURN
                f.finding_id
                    AS finding_id,
                f.status
                    AS status,
                f.review_notes
                    AS review_notes,
                f.reviewed_at
                    AS reviewed_at
            """,
            finding_id=finding_id,
            status=status,
            review_notes=review_notes,
        )

        record = result.single()

        if record is None:
            return None

        data = record.data()

        data["reviewed_at"] = (
            to_python_datetime(
                data.get("reviewed_at")
            )
        )

        return data